import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

//*************************
//Code Generated by JGuiD
//*************************

public class UPLGUI extends JFrame implements ActionListener 
{
	//UPL encObj = new UPL();
	
	
	
//[StartVariables]
	JPanel MYPANEL = new JPanel(null); //layout
 	JTextField txtSearch = new JTextField();
	JButton btnSearch = new JButton();
	JScrollPane scrDriverTable;
	JPanel TABLE = new JPanel();
	JPanel ADD = new JPanel();
	JTabbedPane jtp = new JTabbedPane();

//[EndVariables]
public void TabbedPane()
{
	setTitle("Tabbed Pane");
	setSize(1000, 800);
	getContentPane().add(jtp);
	CREATEMYPANEL();
	jtp.addTab("Table", TABLE);
	jtp.addTab("Add", ADD);
	jtp.setEnabled(0,true);
	
}


public void CREATETABLE()
{
	
	
	String[] columnNames ={"Position", "Username", "Constructor", "Points"};
	
	Object[][] data={
		{"1", "Ben", "Mercedes", "25"},
		{"2", "Chris", "Red Bull", "18"},
		{"3", "Adi", "Ferrari", "15"}
	};
	
	JTable tblDriver = new JTable(data, columnNames);
	tblDriver.setSize(400,200);
	tblDriver.setAutoCreateRowSorter(true);
	tblDriver.setForeground(Color.white);
	tblDriver.setBackground(new Color(0, 102, 204));
	scrDriverTable = new JScrollPane(tblDriver);
	
	 
				
}

//[StartIntialization]
public void CREATEMYPANEL()
{
	txtSearch.setLocation(2010,0);
	txtSearch.setSize(400,100);
	txtSearch.setForeground( new Color(0, 0, 0) );
	txtSearch.setBackground( new Color(255, 255, 255) );
	txtSearch.setToolTipText("Search for a value");
	TABLE.add(txtSearch);

	btnSearch.setLocation(2010,105);
	btnSearch.setSize(400,100);
	btnSearch.setForeground( new Color(0, 0, 0) );
	btnSearch.addActionListener(this);
	btnSearch.setBackground( new Color(255, 255, 255) );
	btnSearch.setText("Search");
	TABLE.add(btnSearch);

	CREATETABLE();
	scrDriverTable.setLocation(0,0);
	scrDriverTable.setSize(2000,200);
	scrDriverTable.setForeground( new Color(-200200200) );
	scrDriverTable.setOpaque(true);
	scrDriverTable.setBackground( new Color(-000) );
	TABLE.add(scrDriverTable);

}
//[EndIntialization]


public void actionPerformed(ActionEvent e)
{
//[StartActions]
	
	
	
//[EndActions]
}

 
public static void main(String[] args )
{
	UPLGUI gd = new UPLGUI();
	gd.TabbedPane();
}
 
}  
